name: "Register workflow check"
description: "Action to register workflow check with workflow-service"
branding:
    icon: "check-circle"
    color: "white"
inputs:
    callback_action:
        description: "Callback action, can be: [register, completed]"
        required: true
    job_status:
        description: "The current status of the job. Possible values are success, failure, or cancelled."
        required: false
runs:
    using: "composite"
    steps:
        - run: ${{ github.action_path }}/callback.sh '${{ toJson(github) }}'
          shell: bash
          env:
              CALLBACK_ACTION: ${{ inputs.callback_action}}
              JOB_STATUS: ${{ inputs.job_status}}
