name: Linter

on:
  repository_dispatch:
    types: [org-workflow-bot]

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: cbrix-company/.cbrix@main
      with:
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        centralized_repo_run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
        tenant_id: ${{ github.event.client_payload.tenant_id }}
        owner: ${{ github.event.client_payload.owner }}
        original_repo: ${{ github.event.client_payload.original_repo_name }}
  linter:
    needs: register
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.original_repo_full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Analysing the code with flake8
      run: |
        flake8 . | tee flake8.txt
        flake8 . 

    - name: Upload flake8.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: flake8 report
        path: flake8.txt
