name: Centralized Linter

on:
  repository_dispatch:
    types: [activate-workflow]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Register
      uses:  shlomis-playground/.cbrix@main
      with:
        callback_action: register
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.full_repo_path }}
        ref: ${{ github.event.client_payload.commit_sha }}
        token: ${{ github.event.client_payload.github_token }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Analysing the code with flake8
      run: |
        flake8 . | tee flake8.txt
        flake8 . 
    - name: Upload flake8.txt as artifact
      uses: actions/upload-artifact@v2
      with:
        name: flake8 report
        path: flake8.txt
    - name: Complete
      if: always()
      uses: shlomis-playground/.cbrix@main
      with:
        callback_action: completed
        job_status: ${{ job.status }}
