name: Centralized Security
# Generated according to "MVS Plan for Serverless"

on:
  repository_dispatch:
    types: [activate-workflow]

jobs:
  encapsulated-action:
    runs-on: ubuntu-latest
    steps:
    - name: github action
      id: test
      uses: jitsecurity-controls/jit-github-action@encapsulate-action
      with:
        pull_key: ${{ secrets.PULL_KEY }}
        docker_user: ${{ secrets.GHCR_REGISTRY_USER }}
        docker_password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
        target_dir: code/
        security_control: ghcr.io/jitsecurity-controls/control-bandit-slim:latest        
        security_control_args: -r /code -f json -q -ll -iii
