name: Security

on:
  repository_dispatch:
    types: [org-workflow-bot]

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: cbrix-company/.cbrix@main
      with:
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        centralized_repo_run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
        tenant_id: ${{ github.event.client_payload.tenant_id }}
        owner: ${{ github.event.client_payload.owner }}
        original_repo: ${{ github.event.client_payload.original_repo_name }}
        verification_token: ${{ github.event.client_payload.verification_token }}

  secrets:
    needs: register
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.original_repo_full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - name: Security check
      run: |
        echo "This is the security check place holder"
