name: Centralized Security

on:
  repository_dispatch:
    types: [activate-workflow]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Register
      uses: cbrix-company/.cbrix@main
      with:
        callback_action: register
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.original_repository }}
        ref: ${{ github.event.client_payload.commit_sha }}
        token: ${{ github.event.client_payload.github_token }}
    - name: Security check
      run: |
        echo "This is the security check place holder"
    - name: Complete
      if: always()
      uses: cbrix-company/.cbrix@main
      with:
        callback_action: completed
        job_status: ${{ job.status }}
