name: Python Tests
env:
  AWS_HOST: localstack
  SERVICES: iam,s3,lambda,apigateway,cloudwatch,events,cloudformation,sts,cognito,secretsmanager,dynamodb,ecr, sqs
  NODE_ENV: test
on:
  repository_dispatch:
    types: [activate-workflow]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Register
      uses: cbrix-dev-playground/.cbrix@main
      with:
        callback_action: register
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.original_repository }}
        ref: ${{ github.event.client_payload.commit_sha }}
        token: ${{ github.event.client_payload.github_token }}
    - name: Unit test
      run: |
        echo "This is the unit test place holder"
    - name: Complete
      if: always()
      uses: cbrix-dev-playground/.cbrix@main
      with:
        callback_action: completed
        job_status: ${{ job.status }}

  mock-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Register
      uses: cbrix-dev-playground/.cbrix@main
      with:
        callback_action: register
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.original_repository }}
        ref: ${{ github.event.client_payload.commit_sha }}
        token: ${{ github.event.client_payload.github_token }}
    - name: Unit test for mock service
      run: |
        echo "This is the unit test for mock service place holder"
    - name: Complete
      if: always()
      uses: cbrix-dev-playground/.cbrix@main
      with:
        callback_action: completed
        job_status: ${{ job.status }}

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Register
      uses: cbrix-dev-playground/.cbrix@main
      with:
        callback_action: register
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.original_repository }}
        ref: ${{ github.event.client_payload.commit_sha }}
        token: ${{ github.event.client_payload.github_token }}
    - name: Integration Test
      run: |
        echo "This is the integration test place holder"
    - name: Complete
      if: always()
      uses: cbrix-dev-playground/.cbrix@main
      with:
        callback_action: completed
        job_status: ${{ job.status }}
