name: Python Tests
env:
  AWS_HOST: localstack
  SERVICES: iam,s3,lambda,apigateway,cloudwatch,events,cloudformation,sts,cognito,secretsmanager,dynamodb,ecr, sqs
  NODE_ENV: test
on:
  repository_dispatch:
    types: [org-workflow-bot]

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: cbrix-company/.cbrix@main
      with:
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        centralized_repo_run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
        tenant_id: ${{ github.event.client_payload.tenant_id }}
        owner: ${{ github.event.client_payload.owner }}
        original_repo: ${{ github.event.client_payload.original_repo_name }}
        verification_token: ${{ github.event.client_payload.verification_token }}

  unit-test:
    needs: register
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.original_repo_full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - name: Unit test
      run: |
        echo "This is the unit test place holder"

  mock-unit-test:
    needs: register
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.original_repo_full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - name: Unit test for mock service
      run: |
        echo "This is the unit test for mock service place holder"

  integration-test:
    needs: register
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.original_repo_full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - name: Integration Test
      run: |
        echo "This is the integration test place holder"
